fix `<%--` begin/end rule
`end` / `name` were incorrectly indented

in my particular implementation of textmate syntax this ended up causing:

```
  File "/tmp/babi/venv/lib/python3.6/site-packages/babi/highlight.py", line 97, in <genexpr>
    for k, v in dct['captures'].items()
ValueError: invalid literal for int() with base 10: 'end'
```